#!/usr/bin/env bash
# Slice 39 — Performance pass stub.
# Measure before optimizing. Run on EAS dev APK + linked backend.
#
# Usage:
#   ./scripts/measure-performance.sh [--output reports/perf-$(date +%Y%m%d).md]
#
# Prerequisites:
#   - EAS dev APK installed on API 34+ emulator or device
#   - Linked Supabase development project
#   - Optional: adb in PATH for Android timing hooks

set -euo pipefail

OUTPUT="${1:-reports/performance-baseline.md}"
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<'EOF'
# Pet Echo — Performance Baseline (Slice 39)

Generated by `scripts/measure-performance.sh` (stub). Replace TBD values after manual measurement.

| Metric | Target (guidance) | Measured | Device | Notes |
|--------|-------------------|----------|--------|-------|
| Cold launch (splash → Home) | < 3s | TBD | | adb shell am start -W |
| Home load (auth → meters visible) | < 2s | TBD | | Network: Wi‑Fi |
| Memory timeline first page | < 1.5s | TBD | | 20 items/page |
| Image upload (5 MB photo) | < 10s | TBD | | Supabase storage |
| Companion generation E2E | < 120s | TBD | | Job polling |
| Dialogue generation | < 5s | TBD | | AI provider |
| Care action RPC latency | < 800ms p95 | TBD | | perform_care_action |
| DB queries per Home load | ≤ 3 | TBD | | React Query + RPC |

## Commands (manual)

```bash
# Cold launch timing (Android)
adb shell am force-stop com.petecho.app
adb shell am start -W -n com.petecho.app/.MainActivity

# Metro / Supabase query logging — enable in development build only
```

## Next steps

1. Fill measured column on physical device and emulator.
2. Profile only metrics exceeding targets.
3. Record build ID and git SHA in PROJECT_STATE.md.
EOF

echo "Wrote performance stub to $OUTPUT"
echo "Slice 39 stub complete — run manual measurements on EAS dev APK."
